curd_All/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace curd_All.Models
{
    public class EmpModel
    {
        public int id { get; set; }
        [Required]
        public string ename { get; set; }
        [Required]

        public string Email { get; set; }
        [Required]

        public string edept { get; set; }
    }
}

curd_All/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace curd_All.Models
{
    public class UserModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]

        public string Email { get; set; }
        [Required]

        public string password { get; set; }
    }
}

curd_All/Controllers/EmpController.cs
using curd_All.Datacon;
using curd_All.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace curd_All.Controllers
{
    public class EmpController : Controller
    {
        // GET: Emp
        public ActionResult Index()
        {
            NeetuEntities obj = new NeetuEntities();
            var res = obj.emps.ToList();
            List<EmpModel> list = new List<EmpModel>();
            foreach (var item in res)
            {
                list.Add(new EmpModel
                {
                    id = item.id,
                    ename = item.ename,
                    Email = item.Email,
                    edept = item.edept,
                });
            }
            return View(list);
        }
        public ActionResult Delete(int id)
        {
            NeetuEntities neetuEntities=new NeetuEntities();
            var rr=neetuEntities.emps.Where(x => x.id == id).First();
            neetuEntities.emps.Remove(rr);
            neetuEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AddEmp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddEmp(EmpModel obj)
        {
            NeetuEntities objcon=new NeetuEntities();
            emp empModel=new emp();
            empModel.id = obj.id;
            empModel.ename = obj.ename;
            empModel.Email = obj.Email;
            empModel.edept = obj.edept;
            if (obj.id == 0)
            {
                objcon.emps.Add(empModel);
                objcon.SaveChanges();
            }
            else
            {
                objcon.Entry(empModel).State=System.Data.Entity.EntityState.Modified;
                objcon.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            NeetuEntities obj = new NeetuEntities();
            var res=obj.emps.Where(x => x.id == id).First();    
            EmpModel empMode=new EmpModel();
            empMode.id = res.id;
            empMode.ename = res.ename;
            empMode.Email = res.Email;
            empMode.edept=res.edept;

            return View( "AddEmp",empMode);
        }
       
            
        
    }
}

curd_All/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace curd_All.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

curd_All/Views/Emp/AddEmp.cshtml
@model curd_All.Models.EmpModel
@{
    ViewBag.Title = "AddEmp";
}

<h2>AddEmp</h2>
<style>
    .error {
        color: red
    }
</style>
@using (Html.BeginForm("AddEmp", "Emp", FormMethod.Post))
{
    @Html.HiddenFor(m=>m.id)
    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(m => m.ename, new { @class = "form-control", placeholder = "Enter your name" })
        @Html.ValidationMessageFor(m => m.ename, "", new { @class = "error" })
    </div>
    <div class="form-group">
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Enter your name" })
        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "error" })
    </div>
    <div class="form-group">
        @Html.TextBoxFor(m => m.edept, new { @class = "form-control", placeholder = "Enter your name" })
        @Html.ValidationMessageFor(m => m.edept, "", new { @class = "error" })
    </div>
    <button class="btn btn-primary" type="submit">AddEmp</button>

}

curd_All/Views/Emp/Index.cshtml
@model List<curd_All.Models.EmpModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table class="table table-bordered table-hover table-responsive">
    <tr>
        <th>Id</th>
        <th>EName</th>
        <th>Email</th>
        <th>Edeprt</th>
        <th>Delete</th>
        <th>Edit</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
        <td>@item.id</td>
        <td>@item.ename</td>
        <td>@item.Email</td>
        <td>@item.edept</td>
            <td><a href="@Url.Action("Delete", "Emp", new {item.id})"class="btn btn-danger">Delete</a></td>
            <td><a href="@Url.Action("Edit", "Emp", new {item.id})"class="btn btn-primary">Edit</a></td>
            </tr>
    }
</table>

curd_All/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

curd_All/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

curd_All/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

curd_All/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>